### ISSUE TITLE
./concuerror --gui crashes on OS X mountain lion

### ISSUE THREAD

**Issue by bdionne** [mariachris/Concuerror#4]
I get the following when running the gui on ML:

`{"init terminating in do_boot",{{load_driver,"No driver found"},[{wxe_server,start,0,   [{file,"wxe_server.erl"},{line,64}]},{wx,new,1,[{file,"wx.erl"},{line,99}]},{gui,start,1,[{file,"src/gui.erl"},{line,39}]},{concuerror,cliAux,1,[{file,"src/concuerror.erl"},{line,129}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}`

I see I have wx-0.99 installed as part of the Erlang distribution (R15B)

Anyone else see this? Presumably I'm missing some underlying native thing that Apple decided to leave out

**Comment by aronisstav** [comment]
Closing this as the repository is discontinued.
